[phases.setup]
nixPkgs = ["python310", "gcc", "openldap", "cyrus_sasl", "postgresql"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn core.wsgi:application"
